name: Publish package

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          cache: maven

      - name: Get latest tag
        id: get_tag
        run: echo "GIT_TAG='echo $(git describe --tags --abbrev=0)'" >> $GITHUB_ENV

      - name: Use the latest tag
        run: echo "The latest tag is $GIT_TAG"

#      - name: Publish to Github Packages
#        run: |
#          mvn versions:set -DnewVersion=${{ steps.get_tag.outputs.TAG }}
#          mvn --batch-mode deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
